# Generated by RepliMap Codify
# Terraform Backend and Provider Configuration

terraform {
  # Local backend (default)
  # For team collaboration, uncomment and configure S3 backend:
  # backend "s3" {
  #   bucket = "my-terraform-state-ACCOUNT_ID"
  #   key    = "replimap-import/terraform.tfstate"
  #   region = "us-west-2"
  #   encrypt = true
  # }

  backend "local" {
    path = "terraform.tfstate"
  }

  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"

  # No default_tags block: it would tag every imported resource with
  # ManagedBy/Source, producing a tag diff on every resource at first
  # `terraform plan` — the opposite of the "0 to change" success criteria
  # this adoption scaffold is built for. Add default_tags yourself once
  # you've decided on a tagging strategy for the adopted resources.
}
