# Generated by RepliMap Codify

resource "aws_cloudfront_distribution" "acmeshop_example_com" {
  aliases = ["acmeshop.example.com", "www.acmeshop.example.com"]
  comment = "Acme Shop storefront"
  default_cache_behavior {
    allowed_methods          = ["GET", "HEAD", "OPTIONS"]
    cache_policy_id          = "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
    cached_methods           = ["GET", "HEAD"]
    compress                 = true
    origin_request_policy_id = "216adef6-5c7f-47e4-b989-5492eafa07d3"
    smooth_streaming         = false
    target_origin_id         = "alb-web"
    viewer_protocol_policy   = "redirect-to-https"
  }
  enabled         = true
  http_version    = "http2and3"
  is_ipv6_enabled = true
  logging_config {
    bucket          = "acme-shop-access-logs.s3.amazonaws.com"
    include_cookies = false
    prefix          = "cloudfront/"
  }
  ordered_cache_behavior {
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cache_policy_id        = "658327ea-f89d-4fab-a63d-7e88639e58f6"
    cached_methods         = ["GET", "HEAD"]
    compress               = true
    path_pattern           = "/static/*"
    smooth_streaming       = false
    target_origin_id       = "s3-static-assets"
    viewer_protocol_policy = "redirect-to-https"
  }
  origin {
    domain_name              = aws_s3_bucket.acme-shop-static-assets.bucket_regional_domain_name
    origin_access_control_id = "E3ACMEOAC000001"
    origin_id                = "s3-static-assets"
  }
  origin {
    custom_header {
      name  = "X-Origin-Verify"
      value = "[REDACTED]"
    }
    custom_origin_config {
      http_port                = 80
      https_port               = 443
      origin_keepalive_timeout = 5
      origin_protocol_policy   = "https-only"
      origin_read_timeout      = 30
      origin_ssl_protocols     = ["TLSv1.2"]
    }
    domain_name = aws_lb.acme_shop_web.dns_name
    origin_id   = "alb-web"
  }
  price_class = "PriceClass_100"
  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  viewer_certificate {
    acm_certificate_arn      = "arn:aws:acm:us-east-1:123456789012:certificate/c0ffee01-aaaa-4bbb-8ccc-0000000000cf"
    minimum_protocol_version = "TLSv1.2_2021"
    ssl_support_method       = "sni-only"
  }
}
