# Generated by RepliMap Codify

resource "aws_acm_certificate" "api_acmeshop_example_com" {
  domain_name   = "api.acmeshop.example.com"
  key_algorithm = "RSA_2048"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  validation_method = "DNS"

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_acm_certificate" "origin_acmeshop_example_com" {
  domain_name   = "origin.acmeshop.example.com"
  key_algorithm = "RSA_2048"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  validation_method = "DNS"

  lifecycle {
    prevent_destroy = true
  }
}
