# Generated by RepliMap Codify

resource "aws_route53_record" "a1b2c3_acmeshop_example_com_cname" {
  name    = "_a1b2c3.acmeshop.example.com"
  records = ["_d4e5f6.acm-validations.aws."]
  ttl     = 300
  type    = "CNAME"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_record" "acmeshop_example_com_a" {
  alias {
    evaluate_target_health = false
    name                   = aws_cloudfront_distribution.acmeshop_example_com.domain_name
    zone_id                = aws_cloudfront_distribution.acmeshop_example_com.hosted_zone_id
  }
  name    = "acmeshop.example.com"
  type    = "A"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_record" "acmeshop_example_com_aaaa" {
  alias {
    evaluate_target_health = false
    name                   = aws_cloudfront_distribution.acmeshop_example_com.domain_name
    zone_id                = aws_cloudfront_distribution.acmeshop_example_com.hosted_zone_id
  }
  name    = "acmeshop.example.com"
  type    = "AAAA"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_record" "acmeshop_example_com_mx" {
  name    = "acmeshop.example.com"
  records = ["10 mail.acmeshop.example.com."]
  ttl     = 3600
  type    = "MX"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_record" "acmeshop_example_com_txt" {
  name    = "acmeshop.example.com"
  records = ["v=spf1 include:amazonses.com ~all"]
  ttl     = 3600
  type    = "TXT"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_record" "api_acmeshop_example_com_a" {
  alias {
    evaluate_target_health = true
    name                   = "d-a1b2c3d4e5.execute-api.us-west-2.amazonaws.com"
    zone_id                = "Z2OJLYMUO9EFXC"
  }
  name    = "api.acmeshop.example.com"
  type    = "A"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_record" "b2c3d4_origin_acmeshop_example_com_cname" {
  name    = "_b2c3d4.origin.acmeshop.example.com"
  records = ["_e5f6a7.acm-validations.aws."]
  ttl     = 300
  type    = "CNAME"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_record" "c3d4e5_api_acmeshop_example_com_cname" {
  name    = "_c3d4e5.api.acmeshop.example.com"
  records = ["_f6a7b8.acm-validations.aws."]
  ttl     = 300
  type    = "CNAME"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_record" "cache_internal_acmeshop_example_com_cname" {
  name    = "cache.internal.acmeshop.example.com"
  records = ["acme-shop-sessions.abc123.0001.usw2.cache.amazonaws.com"]
  ttl     = 60
  type    = "CNAME"
  zone_id = aws_route53_zone.internal_acmeshop_example_com.zone_id
}

resource "aws_route53_record" "db_internal_acmeshop_example_com_cname" {
  name    = "db.internal.acmeshop.example.com"
  records = ["acme-shop-aurora.cluster-c0ffee123456.us-west-2.rds.amazonaws.com"]
  ttl     = 60
  type    = "CNAME"
  zone_id = aws_route53_zone.internal_acmeshop_example_com.zone_id
}

resource "aws_route53_record" "origin_acmeshop_example_com_a" {
  alias {
    evaluate_target_health = true
    name                   = "dualstack.${aws_lb.acme_shop_web.dns_name}"
    zone_id                = aws_lb.acme_shop_web.zone_id
  }
  name    = "origin.acmeshop.example.com"
  type    = "A"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_record" "status_acmeshop_example_com_cname" {
  name    = "status.acmeshop.example.com"
  records = ["acmeshop.statuspage.example.org."]
  ttl     = 300
  type    = "CNAME"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_record" "www_acmeshop_example_com_a" {
  alias {
    evaluate_target_health = false
    name                   = aws_cloudfront_distribution.acmeshop_example_com.domain_name
    zone_id                = aws_cloudfront_distribution.acmeshop_example_com.hosted_zone_id
  }
  name    = "www.acmeshop.example.com"
  type    = "A"
  zone_id = aws_route53_zone.acmeshop_example_com.zone_id
}

resource "aws_route53_zone" "acmeshop_example_com" {
  comment = "Acme Shop public zone"
  name    = "acmeshop.example.com"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_route53_zone" "internal_acmeshop_example_com" {
  comment = "Acme Shop internal names"
  name    = "internal.acmeshop.example.com"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  vpc {
    vpc_id     = aws_vpc.acme-shop-prod.id
    vpc_region = "us-west-2"
  }

  lifecycle {
    prevent_destroy = true
  }
}
