# Generated by RepliMap Codify

resource "aws_dynamodb_table" "acme-shop-orders" {
  attribute {
    name = "pk"
    type = "S"
  }
  attribute {
    name = "sk"
    type = "S"
  }
  attribute {
    name = "status"
    type = "S"
  }
  billing_mode                = "PAY_PER_REQUEST"
  deletion_protection_enabled = true
  global_secondary_index {
    hash_key        = "status"
    name            = "status-index"
    projection_type = "ALL"
  }
  hash_key = "pk"
  name     = "acme-shop-orders"
  point_in_time_recovery {
    enabled = true
  }
  range_key        = "sk"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  ttl {
    attribute_name = "expires_at"
    enabled        = true
  }

  lifecycle {
    prevent_destroy = true
  }
}
