# Generated by RepliMap Codify

resource "aws_ecs_cluster" "acme-shop-prod" {
  name = "acme-shop-prod"
  setting {
    name  = "containerInsights"
    value = "enabled"
  }
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}
