# Generated by RepliMap Codify

resource "aws_elasticache_cluster" "acme-shop-sessions" {
  availability_zone        = "us-west-2a"
  cluster_id               = "acme-shop-sessions"
  engine                   = "redis"
  engine_version           = "7.1"
  maintenance_window       = "mon:06:00-mon:07:00"
  node_type                = "cache.t4g.small"
  num_cache_nodes          = 1
  parameter_group_name     = "default.redis7"
  port                     = 6379
  security_group_ids       = [aws_security_group.acme-shop-redis.id]
  snapshot_retention_limit = 5
  subnet_group_name        = "acme-shop-cache"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_elasticache_subnet_group" "acme-shop-cache" {
  description = "Redis data subnets"
  name        = "acme-shop-cache"
  subnet_ids  = [aws_subnet.acme-shop-data-b.id, aws_subnet.acme-shop-data-a.id]
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}
