# Generated by RepliMap Codify

resource "aws_iam_instance_profile" "acme-shop-web-ec2" {
  name = "acme-shop-web-ec2"
  role = "acme-shop-web-ec2"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_iam_role" "acme-shop-ecs-task" {
  assume_role_policy   = "{\"Statement\": [{\"Action\": \"sts:AssumeRole\", \"Effect\": \"Allow\", \"Principal\": {\"Service\": \"ecs-tasks.amazonaws.com\"}}], \"Version\": \"2012-10-17\"}"
  description          = "ECS task runtime role"
  max_session_duration = 3600
  name                 = "acme-shop-ecs-task"
  path                 = "/"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_iam_role" "acme-shop-ecs-task-execution" {
  assume_role_policy   = "{\"Statement\": [{\"Action\": \"sts:AssumeRole\", \"Effect\": \"Allow\", \"Principal\": {\"Service\": \"ecs-tasks.amazonaws.com\"}}], \"Version\": \"2012-10-17\"}"
  description          = "ECS task execution (pull image, read secrets)"
  max_session_duration = 3600
  name                 = "acme-shop-ecs-task-execution"
  path                 = "/"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_iam_role" "acme-shop-order-stream-fn" {
  assume_role_policy   = "{\"Statement\": [{\"Action\": \"sts:AssumeRole\", \"Effect\": \"Allow\", \"Principal\": {\"Service\": \"lambda.amazonaws.com\"}}], \"Version\": \"2012-10-17\"}"
  description          = "Order stream consumer Lambda"
  max_session_duration = 3600
  name                 = "acme-shop-order-stream-fn"
  path                 = "/"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_iam_role" "acme-shop-orders-api-fn" {
  assume_role_policy   = "{\"Statement\": [{\"Action\": \"sts:AssumeRole\", \"Effect\": \"Allow\", \"Principal\": {\"Service\": \"lambda.amazonaws.com\"}}], \"Version\": \"2012-10-17\"}"
  description          = "Orders API Lambda"
  max_session_duration = 3600
  name                 = "acme-shop-orders-api-fn"
  path                 = "/"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_iam_role" "acme-shop-web-ec2" {
  assume_role_policy   = "{\"Statement\": [{\"Action\": \"sts:AssumeRole\", \"Effect\": \"Allow\", \"Principal\": {\"Service\": \"ec2.amazonaws.com\"}}], \"Version\": \"2012-10-17\"}"
  description          = "EC2 web instances"
  max_session_duration = 3600
  name                 = "acme-shop-web-ec2"
  path                 = "/"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}
