# Generated by RepliMap Codify
# Terraform 1.5+ Import Blocks
#
# These import blocks allow Terraform to adopt existing resources.
#
# Usage:
#   terraform init
#   terraform plan  # Should show: X to import, 0 to add, 0 to change
#   terraform apply
#
# After successful import, you can optionally remove this file.
#

import {
  to = aws_acm_certificate.origin_acmeshop_example_com
  id = "arn:aws:acm:us-west-2:123456789012:certificate/c0ffee02-aaaa-4bbb-8ccc-0000000000a1"
}

import {
  to = aws_acm_certificate.api_acmeshop_example_com
  id = "arn:aws:acm:us-west-2:123456789012:certificate/c0ffee03-aaaa-4bbb-8ccc-0000000000a2"
}

import {
  to = aws_cloudwatch_log_group.ecs_acme-shop-web
  id = "/ecs/acme-shop-web"
}

import {
  to = aws_cloudwatch_log_group.aws_lambda_acme-shop-orders-api
  id = "/aws/lambda/acme-shop-orders-api"
}

import {
  to = aws_cloudwatch_log_group.aws_lambda_acme-shop-order-stream-consumer
  id = "/aws/lambda/acme-shop-order-stream-consumer"
}

import {
  to = aws_cloudwatch_log_group.aws_lambda_acme-shop-order-queue-worker
  id = "/aws/lambda/acme-shop-order-queue-worker"
}

import {
  to = aws_cloudwatch_log_group.aws_apigateway_acme-shop-http-api
  id = "/aws/apigateway/acme-shop-http-api"
}

import {
  to = aws_cloudwatch_log_group.aws_rds_cluster_acme-shop-aurora_slowquery
  id = "/aws/rds/cluster/acme-shop-aurora/slowquery"
}

import {
  to = aws_db_parameter_group.acme-shop-aurora-pg
  id = "acme-shop-aurora-pg"
}

import {
  to = aws_dynamodb_table.acme-shop-orders
  id = "acme-shop-orders"
}

import {
  to = aws_ebs_volume.acme-shop-web-a-root
  id = "vol-ff811cbb54474ccd2"
}

import {
  to = aws_ebs_volume.acme-shop-web-b-root
  id = "vol-0f43ec76408989e96"
}

import {
  to = aws_ebs_volume.acme-shop-bastion-root
  id = "vol-644e8fb21b2c78378"
}

import {
  to = aws_ecr_repository.acme-shop_web
  id = "acme-shop/web"
}

import {
  to = aws_iam_role.acme-shop-ecs-task-execution
  id = "acme-shop-ecs-task-execution"
}

import {
  to = aws_iam_role.acme-shop-ecs-task
  id = "acme-shop-ecs-task"
}

import {
  to = aws_iam_role.acme-shop-web-ec2
  id = "acme-shop-web-ec2"
}

import {
  to = aws_iam_role.acme-shop-orders-api-fn
  id = "acme-shop-orders-api-fn"
}

import {
  to = aws_iam_role.acme-shop-order-stream-fn
  id = "acme-shop-order-stream-fn"
}

import {
  to = aws_s3_bucket.acme-shop-static-assets
  id = "acme-shop-static-assets"
}

import {
  to = aws_s3_bucket.acme-shop-access-logs
  id = "acme-shop-access-logs"
}

import {
  to = aws_s3_bucket.acme-shop-order-exports
  id = "acme-shop-order-exports"
}

import {
  to = aws_sns_topic.acme_shop_order_events
  id = "arn:aws:sns:us-west-2:123456789012:acme-shop-order-events"
}

import {
  to = aws_sqs_queue.acme_shop_order_events
  id = "https://sqs.us-west-2.amazonaws.com/123456789012/acme-shop-order-events"
}

import {
  to = aws_sqs_queue.acme_shop_email_jobs
  id = "https://sqs.us-west-2.amazonaws.com/123456789012/acme-shop-email-jobs"
}

import {
  to = aws_sqs_queue.acme_shop_order_events_dlq
  id = "https://sqs.us-west-2.amazonaws.com/123456789012/acme-shop-order-events-dlq"
}

import {
  to = aws_sqs_queue.acme_shop_email_jobs_dlq
  id = "https://sqs.us-west-2.amazonaws.com/123456789012/acme-shop-email-jobs-dlq"
}

import {
  to = aws_vpc.acme-shop-prod
  id = "vpc-fb3874016d5718a7b"
}

import {
  to = aws_subnet.acme-shop-public-a
  id = "subnet-3bb0afd570fce1aef"
}

import {
  to = aws_subnet.acme-shop-public-b
  id = "subnet-33c61b056a67b03e2"
}

import {
  to = aws_subnet.acme-shop-app-a
  id = "subnet-64814ad4ac60b337f"
}

import {
  to = aws_subnet.acme-shop-app-b
  id = "subnet-cfd30d31c86ff2b01"
}

import {
  to = aws_subnet.acme-shop-data-a
  id = "subnet-c9f5364a1f3751428"
}

import {
  to = aws_subnet.acme-shop-data-b
  id = "subnet-b808d9d0478ed115a"
}

import {
  to = aws_security_group.acme-shop-alb
  id = "sg-40058471c47d39501"
}

import {
  to = aws_security_group.acme-shop-ecs
  id = "sg-606a73056de912684"
}

import {
  to = aws_security_group.acme-shop-web-asg
  id = "sg-0e69eb1459d8a78de"
}

import {
  to = aws_security_group.acme-shop-aurora
  id = "sg-a55e5e7d3230e5830"
}

import {
  to = aws_security_group.acme-shop-redis
  id = "sg-235ee0a2eea509653"
}

import {
  to = aws_security_group.acme-shop-lambda
  id = "sg-9004e17ab2f86e839"
}

import {
  to = aws_security_group.acme-shop-bastion-ssh
  id = "sg-1d822930c582b5545"
}

import {
  to = aws_launch_template.lt-d6c077909491b26ce
  id = "lt-d6c077909491b26ce"
}

import {
  to = aws_lb_target_group.acme-shop-web-ecs
  id = "arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/acme-shop-web-ecs/0a1b2c3d4e5f6071"
}

import {
  to = aws_lb_target_group.acme-shop-web-ec2
  id = "arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/acme-shop-web-ec2/1b2c3d4e5f607182"
}

import {
  to = aws_lb.acme_shop_web
  id = "arn:aws:elasticloadbalancing:us-west-2:123456789012:loadbalancer/app/acme-shop-web/5c1e9a7b3d2f4e60"
}

import {
  to = aws_lb_listener.acme_shop_web_https_443
  id = "arn:aws:elasticloadbalancing:us-west-2:123456789012:listener/app/acme-shop-web/5c1e9a7b3d2f4e60/1a2b3c4d5e6f7081"
}

import {
  to = aws_lb_listener.acme_shop_web_http_80
  id = "arn:aws:elasticloadbalancing:us-west-2:123456789012:listener/app/acme-shop-web/5c1e9a7b3d2f4e60/2b3c4d5e6f708192"
}

import {
  to = aws_autoscaling_group.acme_shop_web_asg
  id = "acme-shop-web-asg"
}

import {
  to = aws_elasticache_subnet_group.acme-shop-cache
  id = "acme-shop-cache"
}

import {
  to = aws_elasticache_cluster.acme-shop-sessions
  id = "acme-shop-sessions"
}

import {
  to = aws_iam_instance_profile.acme-shop-web-ec2
  id = "acme-shop-web-ec2"
}

import {
  to = aws_lambda_event_source_mapping.acme-shop-order-stream-consumer-acme-shop-orders
  id = "11111111-2222-4333-8444-55555555aaaa"
}

import {
  to = aws_lambda_event_source_mapping.acme-shop-order-queue-worker-acme-shop-order-events
  id = "66666666-7777-4888-8999-00000000000a"
}

import {
  to = aws_internet_gateway.acme-shop-igw
  id = "igw-1818fb7347809da78"
}

import {
  to = aws_nat_gateway.nat-d84d439f30742d436
  id = "nat-d84d439f30742d436"
}

import {
  to = aws_route_table.acme-shop-public
  id = "rtb-6e081afa16d445dda"
}

import {
  to = aws_route_table.acme-shop-private
  id = "rtb-3a0bfdd3c8de94b86"
}

import {
  to = aws_route_table.acme-shop-data
  id = "rtb-2fba8080b7dd6d571"
}

import {
  to = aws_vpc_endpoint.acme-shop-s3-gateway
  id = "vpce-2b07d5d139874906f"
}

import {
  to = aws_db_subnet_group.acme-shop-data
  id = "acme-shop-data"
}

import {
  to = aws_rds_cluster.acme-shop-aurora
  id = "acme-shop-aurora"
}

import {
  to = aws_rds_cluster_instance.acme-shop-aurora-1
  id = "acme-shop-aurora-1"
}

import {
  to = aws_rds_cluster_instance.acme-shop-aurora-2
  id = "acme-shop-aurora-2"
}

import {
  to = aws_s3_bucket_policy.acme-shop-static-assets-policy
  id = "acme-shop-static-assets"
}

import {
  to = aws_cloudfront_distribution.acmeshop_example_com
  id = "E2ACMESHOP0001"
}

import {
  to = aws_cloudwatch_metric_alarm.acme-shop-aurora-cpu-high
  id = "acme-shop-aurora-cpu-high"
}

import {
  to = aws_cloudwatch_metric_alarm.acme-shop-aurora-free-memory-low
  id = "acme-shop-aurora-free-memory-low"
}

import {
  to = aws_cloudwatch_metric_alarm.acme-shop-ecs-cpu-high
  id = "acme-shop-ecs-cpu-high"
}

import {
  to = aws_cloudwatch_metric_alarm.acme-shop-alb-5xx
  id = "acme-shop-alb-5xx"
}

import {
  to = aws_cloudwatch_metric_alarm.acme-shop-order-dlq-not-empty
  id = "acme-shop-order-dlq-not-empty"
}

import {
  to = aws_cloudwatch_metric_alarm.acme-shop-orders-api-errors
  id = "acme-shop-orders-api-errors"
}

import {
  to = aws_instance.i-9503494747778cfa3
  id = "i-9503494747778cfa3"
}

import {
  to = aws_kms_key.acme-shop-data
  id = "1b2c3d4e-5f60-4718-9a0b-c1d2e3f4a5b6"
}

import {
  to = aws_kms_alias.alias_acme-shop-data
  id = "alias/acme-shop-data"
}

import {
  to = aws_eip.eipalloc-638f920556a7ffea2
  id = "eipalloc-638f920556a7ffea2"
}

import {
  to = aws_eip.eipalloc-72c8a129af0551560
  id = "eipalloc-72c8a129af0551560"
}

import {
  to = aws_route53_zone.acmeshop_example_com
  id = "Z0ACMESHOP00001EXMPL"
}

import {
  to = aws_route53_record.acmeshop_example_com_a
  id = "Z0ACMESHOP00001EXMPL_acmeshop.example.com_A"
}

import {
  to = aws_route53_record.acmeshop_example_com_aaaa
  id = "Z0ACMESHOP00001EXMPL_acmeshop.example.com_AAAA"
}

import {
  to = aws_route53_record.www_acmeshop_example_com_a
  id = "Z0ACMESHOP00001EXMPL_www.acmeshop.example.com_A"
}

import {
  to = aws_route53_record.origin_acmeshop_example_com_a
  id = "Z0ACMESHOP00001EXMPL_origin.acmeshop.example.com_A"
}

import {
  to = aws_route53_record.api_acmeshop_example_com_a
  id = "Z0ACMESHOP00001EXMPL_api.acmeshop.example.com_A"
}

import {
  to = aws_route53_record.a1b2c3_acmeshop_example_com_cname
  id = "Z0ACMESHOP00001EXMPL__a1b2c3.acmeshop.example.com_CNAME"
}

import {
  to = aws_route53_record.b2c3d4_origin_acmeshop_example_com_cname
  id = "Z0ACMESHOP00001EXMPL__b2c3d4.origin.acmeshop.example.com_CNAME"
}

import {
  to = aws_route53_record.c3d4e5_api_acmeshop_example_com_cname
  id = "Z0ACMESHOP00001EXMPL__c3d4e5.api.acmeshop.example.com_CNAME"
}

import {
  to = aws_route53_record.acmeshop_example_com_mx
  id = "Z0ACMESHOP00001EXMPL_acmeshop.example.com_MX"
}

import {
  to = aws_route53_record.acmeshop_example_com_txt
  id = "Z0ACMESHOP00001EXMPL_acmeshop.example.com_TXT"
}

import {
  to = aws_route53_record.status_acmeshop_example_com_cname
  id = "Z0ACMESHOP00001EXMPL_status.acmeshop.example.com_CNAME"
}

import {
  to = aws_route53_zone.internal_acmeshop_example_com
  id = "Z0ACMESHOP00002EXMPL"
}

import {
  to = aws_route53_record.db_internal_acmeshop_example_com_cname
  id = "Z0ACMESHOP00002EXMPL_db.internal.acmeshop.example.com_CNAME"
}

import {
  to = aws_route53_record.cache_internal_acmeshop_example_com_cname
  id = "Z0ACMESHOP00002EXMPL_cache.internal.acmeshop.example.com_CNAME"
}

import {
  to = aws_secretsmanager_secret.acme-shop_prod_db-credentials
  id = "arn:aws:secretsmanager:us-west-2:123456789012:secret:acme-shop/prod/db-credentials-aB3dEf"
}

import {
  to = aws_secretsmanager_secret.acme-shop_prod_payments-api-key
  id = "arn:aws:secretsmanager:us-west-2:123456789012:secret:acme-shop/prod/payments-api-key-Gh7JkL"
}

import {
  to = aws_ecs_cluster.acme-shop-prod
  id = "acme-shop-prod"
}
