# Generated by RepliMap Codify

resource "aws_kms_alias" "alias_acme-shop-data" {
  name          = "alias/acme-shop-data"
  target_key_id = aws_kms_key.acme-shop-data.key_id
}

resource "aws_kms_key" "acme-shop-data" {
  customer_master_key_spec = "SYMMETRIC_DEFAULT"
  description              = "Acme Shop data-at-rest key (Aurora, secrets, queues)"
  enable_key_rotation      = true
  is_enabled               = true
  key_usage                = "ENCRYPT_DECRYPT"
  multi_region             = false
  policy = jsonencode(
    {
      "Statement" : [
        {
          "Action" : "kms:*",
          "Effect" : "Allow",
          "Principal" : {
            "AWS" : "arn:aws:iam::123456789012:root"
          },
          "Resource" : "*",
          "Sid" : "EnableRootAccountAdmin"
        }
      ],
      "Version" : "2012-10-17"
    }
  )
  rotation_period_in_days = 365
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }

  lifecycle {
    prevent_destroy = true
  }
}
