# Generated by RepliMap Codify

resource "aws_lambda_event_source_mapping" "acme-shop-order-queue-worker-acme-shop-order-events" {
  batch_size                         = 10
  enabled                            = true
  event_source_arn                   = aws_sqs_queue.acme_shop_order_events.arn
  function_name                      = "arn:aws:lambda:us-west-2:123456789012:function:acme-shop-order-queue-worker"
  function_response_types            = ["ReportBatchItemFailures"]
  maximum_batching_window_in_seconds = 5
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_lambda_event_source_mapping" "acme-shop-order-stream-consumer-acme-shop-orders" {
  batch_size                     = 100
  bisect_batch_on_function_error = true
  enabled                        = true
  event_source_arn               = aws_dynamodb_table.acme-shop-orders.stream_arn
  function_name                  = "arn:aws:lambda:us-west-2:123456789012:function:acme-shop-order-stream-consumer"
  maximum_retry_attempts         = 3
  starting_position              = "LATEST"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}
