# Generated by RepliMap Codify

resource "aws_sns_topic" "acme_shop_order_events" {
  display_name      = "acme-shop-order-events"
  fifo_topic        = false
  kms_master_key_id = aws_kms_key.acme-shop-data.arn
  name              = "acme-shop-order-events"
  policy            = jsonencode({})
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_sqs_queue" "acme_shop_email_jobs" {
  content_based_deduplication       = false
  delay_seconds                     = 0
  fifo_queue                        = false
  kms_data_key_reuse_period_seconds = 300
  kms_master_key_id                 = aws_kms_key.acme-shop-data.arn
  max_message_size                  = 262144
  message_retention_seconds         = 345600
  name                              = "acme-shop-email-jobs"
  receive_wait_time_seconds         = 10
  redrive_policy = jsonencode(
    {
      "deadLetterTargetArn" : "arn:aws:sqs:us-west-2:123456789012:acme-shop-email-jobs-dlq",
      "maxReceiveCount" : 5
    }
  )
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  visibility_timeout_seconds = 60

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_sqs_queue" "acme_shop_email_jobs_dlq" {
  content_based_deduplication       = false
  delay_seconds                     = 0
  fifo_queue                        = false
  kms_data_key_reuse_period_seconds = 300
  kms_master_key_id                 = aws_kms_key.acme-shop-data.arn
  max_message_size                  = 262144
  message_retention_seconds         = 1209600
  name                              = "acme-shop-email-jobs-dlq"
  receive_wait_time_seconds         = 10
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  visibility_timeout_seconds = 60

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_sqs_queue" "acme_shop_order_events" {
  content_based_deduplication       = false
  delay_seconds                     = 0
  fifo_queue                        = false
  kms_data_key_reuse_period_seconds = 300
  kms_master_key_id                 = aws_kms_key.acme-shop-data.arn
  max_message_size                  = 262144
  message_retention_seconds         = 345600
  name                              = "acme-shop-order-events"
  receive_wait_time_seconds         = 10
  redrive_policy = jsonencode(
    {
      "deadLetterTargetArn" : "arn:aws:sqs:us-west-2:123456789012:acme-shop-order-events-dlq",
      "maxReceiveCount" : 5
    }
  )
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  visibility_timeout_seconds = 60

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_sqs_queue" "acme_shop_order_events_dlq" {
  content_based_deduplication       = false
  delay_seconds                     = 0
  fifo_queue                        = false
  kms_data_key_reuse_period_seconds = 300
  kms_master_key_id                 = aws_kms_key.acme-shop-data.arn
  max_message_size                  = 262144
  message_retention_seconds         = 1209600
  name                              = "acme-shop-order-events-dlq"
  receive_wait_time_seconds         = 10
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  visibility_timeout_seconds = 60

  lifecycle {
    prevent_destroy = true
  }
}
