# Generated by RepliMap Codify

resource "aws_cloudwatch_log_group" "aws_apigateway_acme-shop-http-api" {
  log_group_class   = "STANDARD"
  name              = "/aws/apigateway/acme-shop-http-api"
  retention_in_days = 30
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_cloudwatch_log_group" "aws_lambda_acme-shop-order-queue-worker" {
  log_group_class   = "STANDARD"
  name              = "/aws/lambda/acme-shop-order-queue-worker"
  retention_in_days = 14
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_cloudwatch_log_group" "aws_lambda_acme-shop-order-stream-consumer" {
  log_group_class   = "STANDARD"
  name              = "/aws/lambda/acme-shop-order-stream-consumer"
  retention_in_days = 14
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_cloudwatch_log_group" "aws_lambda_acme-shop-orders-api" {
  log_group_class   = "STANDARD"
  name              = "/aws/lambda/acme-shop-orders-api"
  retention_in_days = 14
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_cloudwatch_log_group" "aws_rds_cluster_acme-shop-aurora_slowquery" {
  log_group_class   = "STANDARD"
  name              = "/aws/rds/cluster/acme-shop-aurora/slowquery"
  retention_in_days = 90
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_cloudwatch_log_group" "ecs_acme-shop-web" {
  log_group_class   = "STANDARD"
  name              = "/ecs/acme-shop-web"
  retention_in_days = 30
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_cloudwatch_metric_alarm" "acme-shop-alb-5xx" {
  actions_enabled     = true
  alarm_actions       = ["arn:aws:sns:us-west-2:123456789012:acme-shop-alerts"]
  alarm_description   = "acme-shop-alb-5xx breached"
  alarm_name          = "acme-shop-alb-5xx"
  comparison_operator = "GreaterThanThreshold"
  datapoints_to_alarm = 2
  dimensions = {
    LoadBalancer = "app/acme-shop-web/5c1e9a7b3d2f4e60"
  }
  evaluation_periods = 3
  metric_name        = "HTTPCode_ELB_5XX_Count"
  namespace          = "AWS/ApplicationELB"
  period             = 300
  statistic          = "Average"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  threshold          = 25.0
  treat_missing_data = "notBreaching"
}

resource "aws_cloudwatch_metric_alarm" "acme-shop-aurora-cpu-high" {
  actions_enabled     = true
  alarm_actions       = ["arn:aws:sns:us-west-2:123456789012:acme-shop-alerts"]
  alarm_description   = "acme-shop-aurora-cpu-high breached"
  alarm_name          = "acme-shop-aurora-cpu-high"
  comparison_operator = "GreaterThanThreshold"
  datapoints_to_alarm = 2
  dimensions = {
    DBClusterIdentifier = "acme-shop-aurora"
  }
  evaluation_periods = 3
  metric_name        = "CPUUtilization"
  namespace          = "AWS/RDS"
  period             = 300
  statistic          = "Average"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  threshold          = 80.0
  treat_missing_data = "notBreaching"
}

resource "aws_cloudwatch_metric_alarm" "acme-shop-aurora-free-memory-low" {
  actions_enabled     = true
  alarm_actions       = ["arn:aws:sns:us-west-2:123456789012:acme-shop-alerts"]
  alarm_description   = "acme-shop-aurora-free-memory-low breached"
  alarm_name          = "acme-shop-aurora-free-memory-low"
  comparison_operator = "LessThanThreshold"
  datapoints_to_alarm = 2
  dimensions = {
    DBClusterIdentifier = "acme-shop-aurora"
  }
  evaluation_periods = 3
  metric_name        = "FreeableMemory"
  namespace          = "AWS/RDS"
  period             = 300
  statistic          = "Average"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  threshold          = 1000000000.0
  treat_missing_data = "notBreaching"
}

resource "aws_cloudwatch_metric_alarm" "acme-shop-ecs-cpu-high" {
  actions_enabled     = true
  alarm_actions       = ["arn:aws:sns:us-west-2:123456789012:acme-shop-alerts"]
  alarm_description   = "acme-shop-ecs-cpu-high breached"
  alarm_name          = "acme-shop-ecs-cpu-high"
  comparison_operator = "GreaterThanThreshold"
  datapoints_to_alarm = 2
  dimensions = {
    ClusterName = "acme-shop-prod"
    ServiceName = "acme-shop-web"
  }
  evaluation_periods = 3
  metric_name        = "CPUUtilization"
  namespace          = "AWS/ECS"
  period             = 300
  statistic          = "Average"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  threshold          = 75.0
  treat_missing_data = "notBreaching"
}

resource "aws_cloudwatch_metric_alarm" "acme-shop-order-dlq-not-empty" {
  actions_enabled     = true
  alarm_actions       = ["arn:aws:sns:us-west-2:123456789012:acme-shop-alerts"]
  alarm_description   = "acme-shop-order-dlq-not-empty breached"
  alarm_name          = "acme-shop-order-dlq-not-empty"
  comparison_operator = "GreaterThanThreshold"
  datapoints_to_alarm = 2
  dimensions = {
    QueueName = "acme-shop-order-events-dlq"
  }
  evaluation_periods = 3
  metric_name        = "ApproximateNumberOfMessagesVisible"
  namespace          = "AWS/SQS"
  period             = 300
  statistic          = "Average"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  threshold          = 0.0
  treat_missing_data = "notBreaching"
}

resource "aws_cloudwatch_metric_alarm" "acme-shop-orders-api-errors" {
  actions_enabled     = true
  alarm_actions       = ["arn:aws:sns:us-west-2:123456789012:acme-shop-alerts"]
  alarm_description   = "acme-shop-orders-api-errors breached"
  alarm_name          = "acme-shop-orders-api-errors"
  comparison_operator = "GreaterThanThreshold"
  datapoints_to_alarm = 2
  dimensions = {
    FunctionName = "acme-shop-orders-api"
  }
  evaluation_periods = 3
  metric_name        = "Errors"
  namespace          = "AWS/Lambda"
  period             = 300
  statistic          = "Average"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  threshold          = 5.0
  treat_missing_data = "notBreaching"
}
