# Generated by RepliMap Codify

resource "aws_db_parameter_group" "acme-shop-aurora-pg" {
  description = "Acme Shop Aurora instance parameters"
  family      = "aurora-mysql8.0"
  name        = "acme-shop-aurora-pg"
  parameter {
    apply_method = "immediate"
    name         = "slow_query_log"
    value        = "1"
  }
  parameter {
    apply_method = "immediate"
    name         = "long_query_time"
    value        = "2"
  }
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_db_subnet_group" "acme-shop-data" {
  description = "Aurora data subnets"
  name        = "acme-shop-data"
  subnet_ids  = [aws_subnet.acme-shop-data-a.id, aws_subnet.acme-shop-data-b.id]
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
}

resource "aws_rds_cluster" "acme-shop-aurora" {
  backup_retention_period             = 14
  cluster_identifier                  = "acme-shop-aurora"
  copy_tags_to_snapshot               = true
  database_name                       = "shop"
  db_cluster_parameter_group_name     = "default.aurora-mysql8.0"
  db_subnet_group_name                = aws_db_subnet_group.acme-shop-data.name
  deletion_protection                 = true
  enabled_cloudwatch_logs_exports     = ["error", "slowquery"]
  engine                              = "aurora-mysql"
  engine_mode                         = "provisioned"
  engine_version                      = "8.0.mysql_aurora.3.05.2"
  iam_database_authentication_enabled = false
  kms_key_id                          = aws_kms_key.acme-shop-data.arn
  master_username                     = "shop_admin"
  port                                = 3306
  preferred_backup_window             = "03:00-04:00"
  preferred_maintenance_window        = "sun:04:30-sun:05:30"
  storage_encrypted                   = true
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  vpc_security_group_ids = [aws_security_group.acme-shop-aurora.id]

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_rds_cluster_instance" "acme-shop-aurora-1" {
  auto_minor_version_upgrade   = true
  availability_zone            = "us-west-2a"
  cluster_identifier           = aws_rds_cluster.acme-shop-aurora.id
  copy_tags_to_snapshot        = false
  db_parameter_group_name      = "acme-shop-aurora-pg"
  engine                       = "aurora-mysql"
  engine_version               = "8.0.mysql_aurora.3.05.2"
  identifier                   = "acme-shop-aurora-1"
  instance_class               = "db.r6g.large"
  monitoring_interval          = 60
  performance_insights_enabled = true
  promotion_tier               = 0
  publicly_accessible          = false
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_rds_cluster_instance" "acme-shop-aurora-2" {
  auto_minor_version_upgrade   = true
  availability_zone            = "us-west-2b"
  cluster_identifier           = aws_rds_cluster.acme-shop-aurora.id
  copy_tags_to_snapshot        = false
  db_parameter_group_name      = "acme-shop-aurora-pg"
  engine                       = "aurora-mysql"
  engine_version               = "8.0.mysql_aurora.3.05.2"
  identifier                   = "acme-shop-aurora-2"
  instance_class               = "db.r6g.large"
  monitoring_interval          = 60
  performance_insights_enabled = true
  promotion_tier               = 1
  publicly_accessible          = false
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }

  lifecycle {
    prevent_destroy = true
  }
}
