# Generated by RepliMap Codify

resource "aws_s3_bucket" "acme-shop-access-logs" {
  bucket = "acme-shop-access-logs"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_s3_bucket" "acme-shop-order-exports" {
  bucket = "acme-shop-order-exports"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_s3_bucket" "acme-shop-static-assets" {
  bucket = "acme-shop-static-assets"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_s3_bucket_policy" "acme-shop-static-assets-policy" {
  bucket = "acme-shop-static-assets"
  policy = "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Sid\": \"AllowCloudFrontOAC\", \"Effect\": \"Allow\", \"Principal\": {\"Service\": \"cloudfront.amazonaws.com\"}, \"Action\": \"s3:GetObject\", \"Resource\": \"arn:aws:s3:::acme-shop-static-assets/*\", \"Condition\": {\"StringEquals\": {\"AWS:SourceArn\": \"arn:aws:cloudfront::123456789012:distribution/E2ACMESHOP0001\"}}}]}"
}
