# Generated by RepliMap Codify

resource "aws_secretsmanager_secret" "acme-shop_prod_db-credentials" {
  description = "Aurora application credentials"
  kms_key_id  = aws_kms_key.acme-shop-data.arn
  name        = "acme-shop/prod/db-credentials"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_secretsmanager_secret" "acme-shop_prod_payments-api-key" {
  description = "Payment provider API key"
  kms_key_id  = aws_kms_key.acme-shop-data.arn
  name        = "acme-shop/prod/payments-api-key"
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }

  lifecycle {
    prevent_destroy = true
  }
}
