# Generated by RepliMap Codify

resource "aws_ebs_volume" "acme-shop-bastion-root" {
  availability_zone = "us-west-2a"
  encrypted         = true
  iops              = 3000
  size              = 20
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Name        = "acme-shop-bastion-root"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  throughput = 125
  type       = "gp3"

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_ebs_volume" "acme-shop-web-a-root" {
  availability_zone = "us-west-2a"
  encrypted         = true
  iops              = 3000
  size              = 30
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Name        = "acme-shop-web-a-root"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  throughput = 125
  type       = "gp3"

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_ebs_volume" "acme-shop-web-b-root" {
  availability_zone = "us-west-2b"
  encrypted         = true
  iops              = 3000
  size              = 30
  tags = {
    CostCenter  = "cc-1042"
    Environment = "prod"
    Name        = "acme-shop-web-b-root"
    Owner       = "platform-team"
    Project     = "acme-shop"
  }
  throughput = 125
  type       = "gp3"

  lifecycle {
    prevent_destroy = true
  }
}
