# Generated by RepliMap Codify
# Variable Definitions

# =============================================================================
# Common Variables
# =============================================================================

variable "aws_region" {
  description = "AWS region for deployment"
  type        = string
  default     = "us-west-2"
}
