#!/bin/bash
# sync-config.sh - Sync shared configuration from packages/config to CLI
#
# This script copies the generated Python configuration from the shared
# config package to the CLI's _generated directory.

set -e

# Use git to find the monorepo root (robust against directory changes)
REPO_ROOT="$(git rev-parse --show-toplevel)"
CONFIG_PY="$REPO_ROOT/packages/config/dist/config.py"
TARGET_DIR="$REPO_ROOT/apps/cli/replimap/_generated"

echo "Syncing config..."
echo "  Monorepo Root: $REPO_ROOT"

# Create _generated directory if it doesn't exist
mkdir -p "$TARGET_DIR"

# Check if config.py exists in the source
if [ -f "$CONFIG_PY" ]; then
    cp "$CONFIG_PY" "$TARGET_DIR/config.py"
    echo "Synced config.py to $TARGET_DIR"
else
    echo "Error: Source config not found at $CONFIG_PY"
    echo "  Action Required: Run 'pnpm --filter @replimap/config build' first"
    exit 1
fi

# Ensure __init__.py exists
if [ ! -f "$TARGET_DIR/__init__.py" ]; then
    cat > "$TARGET_DIR/__init__.py" << 'EOF'
# AUTO-GENERATED - Do not edit manually
# This file is generated by sync-config.sh
EOF
    echo "Created __init__.py"
fi

echo "Config sync complete"
