name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        We love hearing your ideas! Please describe your feature request.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of RepliMap would this affect?
      options:
        - CLI (`replimap` command)
        - Web Dashboard
        - API
        - New Component
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's your use case?
      placeholder: |
        As a DevOps engineer, I often need to compare two AWS environments...
        Currently, I have to manually export and diff the resources...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        A new command like `replimap diff --source prod --target staging` that:
        1. Scans both environments
        2. Shows a side-by-side comparison
        3. Highlights differences
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've tried?
      placeholder: |
        I tried using terraform plan to compare, but it requires the state files...

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Important for my workflow
        - Critical / Blocking
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this?
      options:
        - label: I'd be interested in implementing this feature
        - label: I can help test this feature
        - label: I can help write documentation
