# Generated by RepliMap
# Useful outputs for reference

output "public_id" {
  description = "ID of VPC public"
  value       = aws_vpc.public.id
}

output "lifesupport_id" {
  description = "ID of VPC lifesupport"
  value       = aws_vpc.lifesupport.id
}

output "stage_id" {
  description = "ID of VPC stage"
  value       = aws_vpc.stage.id
}
