# Generated by RepliMap
# Useful outputs for reference

output "public_id" {
  description = "ID of VPC public"
  value       = aws_vpc.public.id
}

output "lifesupport_id" {
  description = "ID of VPC lifesupport"
  value       = aws_vpc.lifesupport.id
}

output "stage_id" {
  description = "ID of VPC stage"
  value       = aws_vpc.stage.id
}

output "database-1-instance-1_endpoint" {
  description = "Endpoint for RDS instance database-1-instance-1"
  value       = aws_db_instance.database-1-instance-1.endpoint
}

output "database-1-instance-1-upgrade-80_endpoint" {
  description = "Endpoint for RDS instance database-1-instance-1-upgrade-80"
  value       = aws_db_instance.database-1-instance-1-upgrade-80.endpoint
}

output "database-1-instance-2_endpoint" {
  description = "Endpoint for RDS instance database-1-instance-2"
  value       = aws_db_instance.database-1-instance-2.endpoint
}

output "database-1-instance-2-upgrade-80_endpoint" {
  description = "Endpoint for RDS instance database-1-instance-2-upgrade-80"
  value       = aws_db_instance.database-1-instance-2-upgrade-80.endpoint
}

output "database-2-reader-upgrade-80_endpoint" {
  description = "Endpoint for RDS instance database-2-reader-upgrade-80"
  value       = aws_db_instance.database-2-reader-upgrade-80.endpoint
}

output "database-2-reader-upgrade-80-griffith_endpoint" {
  description = "Endpoint for RDS instance database-2-reader-upgrade-80-griffith"
  value       = aws_db_instance.database-2-reader-upgrade-80-griffith.endpoint
}

output "database-2-writer-upgrade-80_endpoint" {
  description = "Endpoint for RDS instance database-2-writer-upgrade-80"
  value       = aws_db_instance.database-2-writer-upgrade-80.endpoint
}

output "database-2-writer-upgrade-80-griffith_endpoint" {
  description = "Endpoint for RDS instance database-2-writer-upgrade-80-griffith"
  value       = aws_db_instance.database-2-writer-upgrade-80-griffith.endpoint
}

output "ecentre-stage_endpoint" {
  description = "Endpoint for RDS instance ecentre-stage"
  value       = aws_db_instance.ecentre-stage.endpoint
}

output "elementorg-sa-burnoffs_endpoint" {
  description = "Endpoint for RDS instance elementorg-sa-burnoffs"
  value       = aws_db_instance.elementorg-sa-burnoffs.endpoint
}

output "eorg-griffith-stage_endpoint" {
  description = "Endpoint for RDS instance eorg-griffith-stage"
  value       = aws_db_instance.eorg-griffith-stage.endpoint
}

output "eorg-griffith-test_endpoint" {
  description = "Endpoint for RDS instance eorg-griffith-test"
  value       = aws_db_instance.eorg-griffith-test.endpoint
}

output "eorg-leeton-stage_endpoint" {
  description = "Endpoint for RDS instance eorg-leeton-stage"
  value       = aws_db_instance.eorg-leeton-stage.endpoint
}

output "eorg-leeton-sandbox_endpoint" {
  description = "Endpoint for RDS instance eorg-leeton-sandbox"
  value       = aws_db_instance.eorg-leeton-sandbox.endpoint
}

output "eorg-ngsc-stage_endpoint" {
  description = "Endpoint for RDS instance eorg-ngsc-stage"
  value       = aws_db_instance.eorg-ngsc-stage.endpoint
}

output "eorg-ngsc-test_endpoint" {
  description = "Endpoint for RDS instance eorg-ngsc-test"
  value       = aws_db_instance.eorg-ngsc-test.endpoint
}

output "eorg-ngsc-test-trellis_endpoint" {
  description = "Endpoint for RDS instance eorg-ngsc-test-trellis"
  value       = aws_db_instance.eorg-ngsc-test-trellis.endpoint
}

output "eorg-ypc-stage_endpoint" {
  description = "Endpoint for RDS instance eorg-ypc-stage"
  value       = aws_db_instance.eorg-ypc-stage.endpoint
}

output "eorg-ypc-test_endpoint" {
  description = "Endpoint for RDS instance eorg-ypc-test"
  value       = aws_db_instance.eorg-ypc-test.endpoint
}

output "esup-stage_endpoint" {
  description = "Endpoint for RDS instance esup-stage"
  value       = aws_db_instance.esup-stage.endpoint
}

output "etime-14si-stage_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage.endpoint
}

output "etime-14si-stage_1_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_1.endpoint
}

output "etime-14si-stage_2_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_2.endpoint
}

output "etime-14si-stage_3_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_3.endpoint
}

output "etime-14si-stage_4_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_4.endpoint
}

output "etime-14si-stage_5_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_5.endpoint
}

output "etime-14si-stage_6_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_6.endpoint
}

output "etime-14si-stage_7_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_7.endpoint
}

output "etime-14si-stage_8_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_8.endpoint
}

output "etime-14si-stage_9_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_9.endpoint
}

output "etime-14si-stage_10_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_10.endpoint
}

output "etime-14si-stage_11_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_11.endpoint
}

output "etime-14si-stage_12_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_12.endpoint
}

output "etime-14si-stage_13_endpoint" {
  description = "Endpoint for RDS instance etime-14si-stage"
  value       = aws_db_instance.etime-14si-stage_13.endpoint
}

output "etime-14si-test_endpoint" {
  description = "Endpoint for RDS instance etime-14si-test"
  value       = aws_db_instance.etime-14si-test.endpoint
}

output "postgresql-11-1_endpoint" {
  description = "Endpoint for RDS instance postgresql-11-1"
  value       = aws_db_instance.postgresql-11-1.endpoint
}

output "test-database-3-instance-1-tmp-04_endpoint" {
  description = "Endpoint for RDS instance test-database-3-instance-1-tmp-04"
  value       = aws_db_instance.test-database-3-instance-1-tmp-04.endpoint
}

output "test-database-3-instance-2-tmp-04_endpoint" {
  description = "Endpoint for RDS instance test-database-3-instance-2-tmp-04"
  value       = aws_db_instance.test-database-3-instance-2-tmp-04.endpoint
}

output "test-docdb-etime_endpoint" {
  description = "Endpoint for RDS instance test-docdb-etime"
  value       = aws_db_instance.test-docdb-etime.endpoint
}

output "arn_aws_elasticloadbalancing_ap-southeast-2_542859091916_loadbalancer_app_elementCentreALB_611395c52f98bcab_dns_name" {
  description = "DNS name for Load Balancer arn:aws:elasticloadbalancing:ap-southeast-2:542859091916:loadbalancer/app/elementCentreALB/611395c52f98bcab"
  value       = aws_lb.arn_aws_elasticloadbalancing_ap-southeast-2_542859091916_loadbalancer_app_elementCentreALB_611395c52f98bcab.dns_name
}

output "arn_aws_elasticloadbalancing_ap-southeast-2_542859091916_loadbalancer_app_elementStaffALB_f2cdbd427fdab333_dns_name" {
  description = "DNS name for Load Balancer arn:aws:elasticloadbalancing:ap-southeast-2:542859091916:loadbalancer/app/elementStaffALB/f2cdbd427fdab333"
  value       = aws_lb.arn_aws_elasticloadbalancing_ap-southeast-2_542859091916_loadbalancer_app_elementStaffALB_f2cdbd427fdab333.dns_name
}

output "arn_aws_elasticloadbalancing_ap-southeast-2_542859091916_loadbalancer_app_elementREC_953437bbb066b95d_dns_name" {
  description = "DNS name for Load Balancer arn:aws:elasticloadbalancing:ap-southeast-2:542859091916:loadbalancer/app/elementREC/953437bbb066b95d"
  value       = aws_lb.arn_aws_elasticloadbalancing_ap-southeast-2_542859091916_loadbalancer_app_elementREC_953437bbb066b95d.dns_name
}

output "arn_aws_elasticloadbalancing_ap-southeast-2_542859091916_loadbalancer_app_elementTIME-ALB_9f79c2e3052977f1_dns_name" {
  description = "DNS name for Load Balancer arn:aws:elasticloadbalancing:ap-southeast-2:542859091916:loadbalancer/app/elementTIME-ALB/9f79c2e3052977f1"
  value       = aws_lb.arn_aws_elasticloadbalancing_ap-southeast-2_542859091916_loadbalancer_app_elementTIME-ALB_9f79c2e3052977f1.dns_name
}

output "arn_aws_elasticloadbalancing_ap-southeast-2_542859091916_loadbalancer_app_TestALB_077cfb0024f98bfd_dns_name" {
  description = "DNS name for Load Balancer arn:aws:elasticloadbalancing:ap-southeast-2:542859091916:loadbalancer/app/TestALB/077cfb0024f98bfd"
  value       = aws_lb.arn_aws_elasticloadbalancing_ap-southeast-2_542859091916_loadbalancer_app_TestALB_077cfb0024f98bfd.dns_name
}

output "alb-elementtime-test_dns_name" {
  description = "DNS name for Load Balancer alb-elementtime-test"
  value       = aws_lb.alb-elementtime-test.dns_name
}

output "alb-elementtime-test-socket_dns_name" {
  description = "DNS name for Load Balancer alb-elementtime-test-socket"
  value       = aws_lb.alb-elementtime-test-socket.dns_name
}

output "alb-elementtime-stage_dns_name" {
  description = "DNS name for Load Balancer alb-elementtime-stage"
  value       = aws_lb.alb-elementtime-stage.dns_name
}

output "alb-elementtime-stage-socket_dns_name" {
  description = "DNS name for Load Balancer alb-elementtime-stage-socket"
  value       = aws_lb.alb-elementtime-stage-socket.dns_name
}

output "alb-elementtime-stage_1_dns_name" {
  description = "DNS name for Load Balancer alb-elementtime-stage"
  value       = aws_lb.alb-elementtime-stage_1.dns_name
}

output "alb-elementtime-stage-socket_1_dns_name" {
  description = "DNS name for Load Balancer alb-elementtime-stage-socket"
  value       = aws_lb.alb-elementtime-stage-socket_1.dns_name
}

output "alb-eodefault-leeton-sandbox_dns_name" {
  description = "DNS name for Load Balancer alb-eodefault-leeton-sandbox"
  value       = aws_lb.alb-eodefault-leeton-sandbox.dns_name
}

output "alb-eodefault-sa-fires_dns_name" {
  description = "DNS name for Load Balancer alb-eodefault-sa-fires"
  value       = aws_lb.alb-eodefault-sa-fires.dns_name
}

output "alb-elementsup-stage_dns_name" {
  description = "DNS name for Load Balancer alb-elementsup-stage"
  value       = aws_lb.alb-elementsup-stage.dns_name
}

output "alb-ghostrpc-stage_dns_name" {
  description = "DNS name for Load Balancer alb-ghostrpc-stage"
  value       = aws_lb.alb-ghostrpc-stage.dns_name
}

output "alb-elementcentre-stage_dns_name" {
  description = "DNS name for Load Balancer alb-elementcentre-stage"
  value       = aws_lb.alb-elementcentre-stage.dns_name
}

output "alb-elementrec-stage_dns_name" {
  description = "DNS name for Load Balancer alb-elementrec-stage"
  value       = aws_lb.alb-elementrec-stage.dns_name
}

output "alb-elementstaff-stage_dns_name" {
  description = "DNS name for Load Balancer alb-elementstaff-stage"
  value       = aws_lb.alb-elementstaff-stage.dns_name
}

output "alb-etime-test-skt-14si_dns_name" {
  description = "DNS name for Load Balancer alb-etime-test-skt-14si"
  value       = aws_lb.alb-etime-test-skt-14si.dns_name
}

output "alb-etime-stage-14si_dns_name" {
  description = "DNS name for Load Balancer alb-etime-stage-14si"
  value       = aws_lb.alb-etime-stage-14si.dns_name
}

output "alb-etime-stage-skt-14si_dns_name" {
  description = "DNS name for Load Balancer alb-etime-stage-skt-14si"
  value       = aws_lb.alb-etime-stage-skt-14si.dns_name
}

output "alb-etime-stage-14si_1_dns_name" {
  description = "DNS name for Load Balancer alb-etime-stage-14si"
  value       = aws_lb.alb-etime-stage-14si_1.dns_name
}

output "alb-etime-test-14si_dns_name" {
  description = "DNS name for Load Balancer alb-etime-test-14si"
  value       = aws_lb.alb-etime-test-14si.dns_name
}

output "alb-etime-stage-skt-14si_1_dns_name" {
  description = "DNS name for Load Balancer alb-etime-stage-skt-14si"
  value       = aws_lb.alb-etime-stage-skt-14si_1.dns_name
}

output "alb-eodefault-ypc_dns_name" {
  description = "DNS name for Load Balancer alb-eodefault-ypc"
  value       = aws_lb.alb-eodefault-ypc.dns_name
}

output "alb-eodefault-test-ypc_dns_name" {
  description = "DNS name for Load Balancer alb-eodefault-test-ypc"
  value       = aws_lb.alb-eodefault-test-ypc.dns_name
}

output "alb-eodefault-test-ngsc_dns_name" {
  description = "DNS name for Load Balancer alb-eodefault-test-ngsc"
  value       = aws_lb.alb-eodefault-test-ngsc.dns_name
}

output "alb-eodefault-ngsc_dns_name" {
  description = "DNS name for Load Balancer alb-eodefault-ngsc"
  value       = aws_lb.alb-eodefault-ngsc.dns_name
}

output "alb-eodefault-leeton-c5_dns_name" {
  description = "DNS name for Load Balancer alb-eodefault-leeton-c5"
  value       = aws_lb.alb-eodefault-leeton-c5.dns_name
}

output "alb-eo-test-ngsc-trellis_dns_name" {
  description = "DNS name for Load Balancer alb-eo-test-ngsc-trellis"
  value       = aws_lb.alb-eo-test-ngsc-trellis.dns_name
}

output "alb-eodefault-griffith_dns_name" {
  description = "DNS name for Load Balancer alb-eodefault-griffith"
  value       = aws_lb.alb-eodefault-griffith.dns_name
}

output "alb-eodefault-test-griffith_dns_name" {
  description = "DNS name for Load Balancer alb-eodefault-test-griffith"
  value       = aws_lb.alb-eodefault-test-griffith.dns_name
}

output "alb-eodefault-sa-redirect_dns_name" {
  description = "DNS name for Load Balancer alb-eodefault-sa-redirect"
  value       = aws_lb.alb-eodefault-sa-redirect.dns_name
}

output "alb-elementtime-stage-cmd_dns_name" {
  description = "DNS name for Load Balancer alb-elementtime-stage-cmd"
  value       = aws_lb.alb-elementtime-stage-cmd.dns_name
}

output "alb-elementtime-test-cmd_dns_name" {
  description = "DNS name for Load Balancer alb-elementtime-test-cmd"
  value       = aws_lb.alb-elementtime-test-cmd.dns_name
}

output "alb-elementtime-stage-cmd_1_dns_name" {
  description = "DNS name for Load Balancer alb-elementtime-stage-cmd"
  value       = aws_lb.alb-elementtime-stage-cmd_1.dns_name
}

output "alb-etime-stage-cmd-14si_dns_name" {
  description = "DNS name for Load Balancer alb-etime-stage-cmd-14si"
  value       = aws_lb.alb-etime-stage-cmd-14si.dns_name
}

output "alb-etime-stage-cmd-14si_1_dns_name" {
  description = "DNS name for Load Balancer alb-etime-stage-cmd-14si"
  value       = aws_lb.alb-etime-stage-cmd-14si_1.dns_name
}

output "alb-etime-test-cmd-14si_dns_name" {
  description = "DNS name for Load Balancer alb-etime-test-cmd-14si"
  value       = aws_lb.alb-etime-test-cmd-14si.dns_name
}
