# Generated by RepliMap
# Common variables for the replicated environment

variable "environment" {
  description = "Environment name (e.g., staging, dev)"
  type        = string
  default     = "staging"
}

variable "aws_account_id" {
  description = "Target AWS account ID"
  type        = string
}

variable "aws_region" {
  description = "AWS region for deployment"
  type        = string
}

variable "common_tags" {
  description = "Common tags to apply to all resources"
  type        = map(string)
  default     = {}
}
